language: c
compiler:
  - gcc
  - clang
python: 3.9
env:
  matrix:
    - TRAVIS_PYTHON_VERSION=2.7
    - TRAVIS_PYTHON_VERSION=3.7
    - TRAVIS_PYTHON_VERSION=3.6
addons:
  apt:
    packages:
     - libgsl0-dev
before_install:
 # Install lcov
 - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
 - tar xf lcov_1.11.orig.tar.gz
 - mkdir $HOME/usr
 - export PATH=$HOME/usr/bin:$PATH
 - make -C lcov-1.11/ install PREFIX=$HOME
 #Setup conda for faster installs
 - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib setuptools pip pytest
 - source activate test-environment
 - pip install 'coverage==4.1' --force-reinstall # necessary bc of backward incompatible change in 4.2 about combining reports
 - pip install pytest-cov
 - easy_install --upgrade requests
# Link to OpenMP library for clang
 - export LD_LIBRARY_PATH=$(if [[ $CC == "clang" ]]; then echo -n '/usr/local/clang/lib'; fi)
install:
 - make COVERAGE=1
 - sudo make install
 - make pywrapper
 - export PYTHONPATH=$PYTHONPATH:$PWD/py
 - cd tests/
script:
 - pytest -v test_oned.py test_twod.py test_fix.py test_log.py --cov=extreme_deconvolution --cov-config ../.coveragerc_travis
after_success:
# Codecov
 # Generate lcov output 
 - lcov --capture --directory $HOME/build/jobovy/extreme-deconvolution/src/ --no-external --output-file coverage.info
# Codecov, need to edit bash uploader for incorrect TRAVIS_PYTHON_VERSION environment variable matching, at least until codecov/codecov-bash#133 is resolved
 - curl -s https://codecov.io/bash > .codecov
 - sed -i -e 's/TRAVIS_.*_VERSION/^TRAVIS_.*_VERSION=/' .codecov
 - chmod +x .codecov
 - if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $CC == 'gcc' ]]; then ./.codecov -X gcov; fi
notifications:
  email:
    recipients:
      - jo.bovy@gmail.com
    on_success: change
    on_failure: change
